// quotes.js
// 365 daily affirmations for DaY.ffirmations

const QUOTES = [
  { id: 1, text: "Today I choose to speak to myself with the same kindness I offer others.", tag: "self-kindness" },
  { id: 2, text: "My pace is sacred; I am not late, I am right on time for my own life.", tag: "timing" },
  { id: 3, text: "Even on quiet days, my growth is unfolding beneath the surface.", tag: "growth" },
  { id: 4, text: "I release the need to be perfect and allow myself to simply be.", tag: "self-acceptance" },
  { id: 5, text: "I am allowed to take up space, to rest, and to begin again.", tag: "permission" },
  { id: 6, text: "My worth is not measured by my productivity, but by my existence.", tag: "worth" },
  { id: 7, text: "I trust that small steps taken consistently can reshape my entire path.", tag: "consistency" },
  { id: 8, text: "I can hold both gratitude for where I am and desire for where I’m going.", tag: "gratitude" },
  { id: 9, text: "I am learning to soften my inner voice and strengthen my inner peace.", tag: "inner-peace" },
  { id: 10, text: "I am not behind; I am building a life that feels like mine.", tag: "alignment" },
  { id: 11, text: "My feelings are valid, and I can meet them with gentle curiosity.", tag: "emotions" },
  { id: 12, text: "I am allowed to change my mind, my path, and my story.", tag: "change" },
  { id: 13, text: "Rest is not a reward I earn; it is a right I already have.", tag: "rest" },
  { id: 14, text: "I release comparison and return to the truth of who I am.", tag: "comparison" },
  { id: 15, text: "I am worthy of soft mornings, slow days, and quiet joy.", tag: "softness" },
  { id: 16, text: "I can be a work in progress and still be deeply worthy right now.", tag: "progress" },
  { id: 17, text: "My body is not an enemy to fix, but a home to listen to.", tag: "body" },
  { id: 18, text: "I am allowed to take breaks without apologizing for my needs.", tag: "boundaries" },
  { id: 19, text: "I trust that what is meant for me will not require me to shrink.", tag: "trust" },
  { id: 20, text: "I am learning to celebrate small wins as loudly as big ones.", tag: "celebration" },
  { id: 21, text: "I can hold my own hand through every season of my life.", tag: "self-support" },
  { id: 22, text: "I am allowed to outgrow versions of myself that no longer feel true.", tag: "evolution" },
  { id: 23, text: "I choose thoughts that make my nervous system feel safe.", tag: "safety" },
  { id: 24, text: "I am not defined by my most difficult days.", tag: "resilience" },
  { id: 25, text: "I give myself permission to be both soft and strong.", tag: "strength" },
  { id: 26, text: "I am allowed to take up emotional, physical, and mental space.", tag: "space" },
  { id: 27, text: "I trust that my intuition is a quiet, loyal guide within me.", tag: "intuition" },
  { id: 28, text: "I am learning to rest without guilt and move without pressure.", tag: "balance" },
  { id: 29, text: "I am worthy of love that feels gentle, honest, and steady.", tag: "love" },
  { id: 30, text: "I can start over as many times as I need. There is no limit.", tag: "new-beginnings" },
  { id: 31, text: "I am allowed to be proud of how far I’ve come, even if I’m not yet where I want to be.", tag: "pride" },
  { id: 32, text: "My sensitivity is not a flaw; it is a doorway to deeper connection.", tag: "sensitivity" },
  { id: 33, text: "I am learning to trust the timing of my healing.", tag: "healing" },
  { id: 34, text: "I can release what is heavy and make room for what is light.", tag: "release" },
  { id: 35, text: "I am worthy of taking up time, not just giving it away.", tag: "time" },
  { id: 36, text: "I honor my past without letting it define my future.", tag: "past" },
  { id: 37, text: "I am allowed to be both a masterpiece and a work in progress.", tag: "paradox" },
  { id: 38, text: "I choose to notice small moments of beauty in my day.", tag: "mindfulness" },
  { id: 39, text: "I am learning to respond with intention instead of reacting from fear.", tag: "response" },
  { id: 40, text: "I am worthy of relationships where I feel seen, heard, and safe.", tag: "relationships" },
  { id: 41, text: "I can take up space without explaining why I deserve to be here.", tag: "presence" },
  { id: 42, text: "I am allowed to rest before I am exhausted.", tag: "prevention" },
  { id: 43, text: "I trust that my heart knows when it is time to stay and when it is time to go.", tag: "discernment" },
  { id: 44, text: "I am learning to be gentle with myself on the days I feel behind.", tag: "self-compassion" },
  { id: 45, text: "I am worthy of joy that does not need to be earned.", tag: "joy" },
  { id: 46, text: "I can let go of what I cannot control and return to what I can.", tag: "control" },
  { id: 47, text: "I am allowed to choose peace over proving my point.", tag: "peace" },
  { id: 48, text: "I trust that my path can be different and still be beautiful.", tag: "path" },
  { id: 49, text: "I am learning to listen to my body’s whispers before they become screams.", tag: "listening" },
  { id: 50, text: "I am worthy of a life that feels soft, spacious, and true.", tag: "life" },
  { id: 51, text: "I can be proud of myself for surviving days I thought I couldn’t.", tag: "survival" },
  { id: 52, text: "I am allowed to say no without feeling guilty.", tag: "no" },
  { id: 53, text: "I trust that rest will not make me fall behind; it will help me return stronger.", tag: "recharge" },
  { id: 54, text: "I am learning to replace self-criticism with self-curiosity.", tag: "curiosity" },
  { id: 55, text: "I am worthy of being chosen, including by myself.", tag: "chosen" },
  { id: 56, text: "I can let go of the version of me that only felt lovable when achieving.", tag: "achievement" },
  { id: 57, text: "I am allowed to want more without shaming myself for what I already have.", tag: "desire" },
  { id: 58, text: "I trust that my heart can heal at its own gentle pace.", tag: "heart" },
  { id: 59, text: "I am learning to see my softness as a strength, not a weakness.", tag: "soft-strength" },
  { id: 60, text: "I am worthy of taking up emotional space in my own life.", tag: "emotional-space" },
  { id: 61, text: "I can choose to believe that something good is quietly unfolding for me.", tag: "hope" },
  { id: 62, text: "I am allowed to be both grateful and still want change.", tag: "duality" },
  { id: 63, text: "I trust that my inner voice becomes clearer when I slow down to listen.", tag: "inner-voice" },
  { id: 64, text: "I am learning to forgive myself for not knowing then what I know now.", tag: "forgiveness" },
  { id: 65, text: "I am worthy of boundaries that protect my peace.", tag: "protection" },
  { id: 66, text: "I can release the pressure to have everything figured out right now.", tag: "uncertainty" },
  { id: 67, text: "I am allowed to choose what feels aligned over what looks impressive.", tag: "alignment" },
  { id: 68, text: "I trust that my small daily choices are quietly shaping my future.", tag: "choices" },
  { id: 69, text: "I am learning to see rest as a sacred part of my growth.", tag: "sacred-rest" },
  { id: 70, text: "I am worthy of being loved in my most unpolished moments.", tag: "unpolished" },
  { id: 71, text: "I can let go of stories that tell me I am too much or not enough.", tag: "stories" },
  { id: 72, text: "I am allowed to move slowly and still call it progress.", tag: "slow-progress" },
  { id: 73, text: "I trust that my dreams are valid, even if others don’t understand them.", tag: "dreams" },
  { id: 74, text: "I am learning to celebrate who I am, not just what I do.", tag: "identity" },
  { id: 75, text: "I am worthy of spaces where I don’t have to shrink to fit in.", tag: "belonging" },
  { id: 76, text: "I can choose to see setbacks as redirections, not failures.", tag: "redirection" },
  { id: 77, text: "I am allowed to ask for help without feeling weak.", tag: "help" },
  { id: 78, text: "I trust that my heart can hold both grief and gratitude at once.", tag: "grief" },
  { id: 79, text: "I am learning to speak to myself in a tone that feels like a safe home.", tag: "self-talk" },
  { id: 80, text: "I am worthy of taking up time to heal, not just to perform.", tag: "healing-time" },
  { id: 81, text: "I can let go of rushing and allow my life to unfold in layers.", tag: "unfolding" },
  { id: 82, text: "I am allowed to change my mind about what I want and need.", tag: "needs" },
  { id: 83, text: "I trust that my body is doing its best to keep me safe.", tag: "body-trust" },
  { id: 84, text: "I am learning to honor my limits without shame.", tag: "limits" },
  { id: 85, text: "I am worthy of joy that feels calm, not chaotic.", tag: "calm-joy" },
  { id: 86, text: "I can choose to see my sensitivity as a superpower.", tag: "superpower" },
  { id: 87, text: "I am allowed to rest even when there is more I could do.", tag: "enough" },
  { id: 88, text: "I trust that my inner wisdom grows each time I listen to it.", tag: "wisdom" },
  { id: 89, text: "I am learning to be patient with the parts of me that are still healing.", tag: "patience" },
  { id: 90, text: "I am worthy of a life that feels gentle on my nervous system.", tag: "nervous-system" },
  { id: 91, text: "I can let go of the belief that I must earn my own compassion.", tag: "compassion" },
  { id: 92, text: "I am allowed to choose what nourishes me over what impresses others.", tag: "nourishment" },
  { id: 93, text: "I trust that my path is allowed to look different from what I imagined.", tag: "unexpected" },
  { id: 94, text: "I am learning to see my needs as valid, not inconvenient.", tag: "valid-needs" },
  { id: 95, text: "I am worthy of being gentle with myself when I am learning something new.", tag: "learning" },
  { id: 96, text: "I can choose to believe that I am not too late for my own life.", tag: "not-too-late" },
  { id: 97, text: "I am allowed to create a life that feels soft, slow, and meaningful.", tag: "meaning" },
  { id: 98, text: "I trust that my heart knows how to rebuild after it has been broken.", tag: "rebuild" },
  { id: 99, text: "I am learning to honor my energy instead of pushing past it.", tag: "energy" },
  { id: 100, text: "I am worthy of being loved exactly as I am in this moment.", tag: "as-i-am" },
  { id: 101, text: "I can let go of the pressure to be everything for everyone.", tag: "pressure" },
  { id: 102, text: "I am allowed to choose softness in a world that often chooses hardness.", tag: "soft-choice" },
  { id: 103, text: "I trust that my small acts of courage matter more than I realize.", tag: "courage" },
  { id: 104, text: "I am learning to see my body as a companion, not a project.", tag: "body-companion" },
  { id: 105, text: "I am worthy of taking breaks without explaining why I need them.", tag: "breaks" },
  { id: 106, text: "I can choose to believe that I am already enough, even as I grow.", tag: "enough" },
  { id: 107, text: "I am allowed to walk away from what constantly hurts my spirit.", tag: "walk-away" },
  { id: 108, text: "I trust that my inner child deserves tenderness, not criticism.", tag: "inner-child" },
  { id: 109, text: "I am learning to celebrate my quiet strengths.", tag: "quiet-strength" },
  { id: 110, text: "I am worthy of a life that feels like a soft exhale.", tag: "exhale" },
  { id: 111, text: "I can let go of the belief that I must always be strong for others.", tag: "always-strong" },
  { id: 112, text: "I am allowed to be both healing and happy at the same time.", tag: "healing-and-happy" },
  { id: 113, text: "I trust that my story is still unfolding in beautiful ways.", tag: "story" },
  { id: 114, text: "I am learning to see my boundaries as bridges to healthier connections.", tag: "healthy-boundaries" },
  { id: 115, text: "I am worthy of being understood, not just tolerated.", tag: "understood" },
  { id: 116, text: "I can choose to believe that my presence is a gift.", tag: "presence-gift" },
  { id: 117, text: "I am allowed to rest in the middle, not just at the end.", tag: "mid-rest" },
  { id: 118, text: "I trust that my heart can hold hope even when it feels tired.", tag: "tired-hope" },
  { id: 119, text: "I am learning to speak to myself like someone I love.", tag: "self-love" },
  { id: 120, text: "I am worthy of a life that feels aligned with my values.", tag: "values" },
  { id: 121, text: "I can let go of the idea that healing must look linear.", tag: "nonlinear" },
  { id: 122, text: "I am allowed to choose peace over constant productivity.", tag: "peace-over-productivity" },
  { id: 123, text: "I trust that my inner wisdom grows each time I honor my needs.", tag: "honor-needs" },
  { id: 124, text: "I am learning to see my progress in the small, quiet shifts.", tag: "small-shifts" },
  { id: 125, text: "I am worthy of being loved in my softness, not despite it.", tag: "soft-love" },
  { id: 126, text: "I can choose to believe that I am allowed to take up time to heal.", tag: "healing-permission" },
  { id: 127, text: "I am allowed to say yes to what lights me up and no to what drains me.", tag: "yes-and-no" },
  { id: 128, text: "I trust that my heart knows when it is safe to open again.", tag: "open-heart" },
  { id: 129, text: "I am learning to see my needs as worthy of being met.", tag: "worthy-needs" },
  { id: 130, text: "I am worthy of a life that feels gentle on my soul.", tag: "gentle-life" },
  { id: 131, text: "I can let go of the belief that I must always be okay.", tag: "not-okay" },
  { id: 132, text: "I am allowed to be both grateful for my life and curious about what else is possible.", tag: "possibility" },
  { id: 133, text: "I trust that my inner voice becomes clearer when I create quiet moments.", tag: "quiet-moments" },
  { id: 134, text: "I am learning to see my healing as a journey, not a race.", tag: "healing-journey" },
  { id: 135, text: "I am worthy of being loved in the middle of my becoming.", tag: "becoming" },
  { id: 136, text: "I can choose to believe that I am not too much for the right people.", tag: "right-people" },
  { id: 137, text: "I am allowed to rest without earning it through exhaustion.", tag: "rest-right" },
  { id: 138, text: "I trust that my heart can find softness again after being guarded.", tag: "soft-again" },
  { id: 139, text: "I am learning to see my boundaries as acts of self-respect.", tag: "self-respect" },
  { id: 140, text: "I am worthy of a life that feels like home inside my own body.", tag: "home" },
  { id: 141, text: "I can let go of the belief that I must always be productive to be valuable.", tag: "value" },
  { id: 142, text: "I am allowed to choose slowness in a world that glorifies speed.", tag: "slowness" },
  { id: 143, text: "I trust that my inner guidance is leading me toward what is meant for me.", tag: "guidance" },
  { id: 144, text: "I am learning to see my emotions as messengers, not enemies.", tag: "messengers" },
  { id: 145, text: "I am worthy of being loved in the moments I feel most unlovable.", tag: "unlovable" },
  { id: 146, text: "I can choose to believe that my presence makes a difference.", tag: "difference" },
  { id: 147, text: "I am allowed to rest in the middle of my healing, not just at the end.", tag: "healing-rest" },
  { id: 148, text: "I trust that my heart can hold both fear and courage at the same time.", tag: "fear-and-courage" },
  { id: 149, text: "I am learning to see my softness as a radical act of strength.", tag: "radical-softness" },
  { id: 150, text: "I am worthy of a life that feels gentle, spacious, and true to me.", tag: "true-life" },
  { id: 151, text: "I can let go of the belief that I must always be okay to be loved.", tag: "loved-anyway" },
  { id: 152, text: "I am allowed to choose what feels nourishing over what feels impressive.", tag: "nourishing" },
  { id: 153, text: "I trust that my inner wisdom grows each time I honor my boundaries.", tag: "boundary-wisdom" },
  { id: 154, text: "I am learning to see my progress in the way I speak to myself.", tag: "progress-voice" },
  { id: 155, text: "I am worthy of being loved in the quiet, ordinary moments.", tag: "ordinary" },
  { id: 156, text: "I can choose to believe that I am allowed to take up emotional space.", tag: "emotional-worth" },
  { id: 157, text: "I am allowed to rest without feeling like I must earn it.", tag: "rest-deserve" },
  { id: 158, text: "I trust that my heart knows how to guide me back to myself.", tag: "return" },
  { id: 159, text: "I am learning to see my needs as invitations to care for myself.", tag: "care" },
  { id: 160, text: "I am worthy of a life that feels soft on my nervous system.", tag: "soft-nervous" },
  { id: 161, text: "I can let go of the belief that I must always be strong to be worthy.", tag: "worthy-soft" },
  { id: 162, text: "I am allowed to choose rest, even when the world keeps moving fast.", tag: "rest-choice" },
  { id: 163, text: "I trust that my inner voice becomes clearer when I slow down.", tag: "slow-down" },
  { id: 164, text: "I am learning to see my healing as a gentle unfolding, not a task.", tag: "unfold" },
  { id: 165, text: "I am worthy of being loved in the middle of my uncertainty.", tag: "uncertain-love" },
  { id: 166, text: "I can choose to believe that I am not behind; I am on my own path.", tag: "own-path" },
  { id: 167, text: "I am allowed to rest before I reach my breaking point.", tag: "before-break" },
  { id: 168, text: "I trust that my heart can find new ways to feel safe.", tag: "new-safety" },
  { id: 169, text: "I am learning to see my boundaries as a way of honoring my energy.", tag: "energy-honor" },
  { id: 170, text: "I am worthy of a life that feels like a soft place to land.", tag: "soft-landing" },
  { id: 171, text: "I can let go of the belief that I must always be in control.", tag: "let-go-control" },
  { id: 172, text: "I am allowed to choose what feels aligned over what feels expected.", tag: "expected" },
  { id: 173, text: "I trust that my inner wisdom is always available when I listen.", tag: "always-there" },
  { id: 174, text: "I am learning to see my emotions as waves that move through me.", tag: "waves" },
  { id: 175, text: "I am worthy of being loved in the moments I feel most unsure.", tag: "unsure" },
  { id: 176, text: "I can choose to believe that my presence is enough.", tag: "presence-enough" },
  { id: 177, text: "I am allowed to rest in the middle of my journey, not just at milestones.", tag: "journey-rest" },
  { id: 178, text: "I trust that my heart can hold both doubt and faith at once.", tag: "doubt-faith" },
  { id: 179, text: "I am learning to see my softness as a quiet revolution.", tag: "revolution" },
  { id: 180, text: "I am worthy of a life that feels gentle, honest, and kind.", tag: "gentle-honest" },
  { id: 181, text: "I can let go of the belief that I must always be improving to be enough.", tag: "enough-now" },
  { id: 182, text: "I am allowed to choose what feels true over what feels familiar.", tag: "true-over-familiar" },
  { id: 183, text: "I trust that my inner guidance is leading me toward deeper peace.", tag: "deeper-peace" },
  { id: 184, text: "I am learning to see my healing as a series of small, brave choices.", tag: "brave-choices" },
  { id: 185, text: "I am worthy of being loved in the middle of my becoming, not just at the end.", tag: "mid-becoming" },
  { id: 186, text: "I can choose to believe that I am allowed to take up space in my own life.", tag: "my-space" },
  { id: 187, text: "I am allowed to rest without turning it into another task.", tag: "rest-not-task" },
  { id: 188, text: "I trust that my heart knows how to find its way back to calm.", tag: "back-to-calm" },
  { id: 189, text: "I am learning to see my needs as worthy of tenderness.", tag: "tender-needs" },
  { id: 190, text: "I am worthy of a life that feels soft, steady, and sincere.", tag: "soft-steady" },
  { id: 191, text: "I can let go of the belief that I must always be okay to be worthy.", tag: "worthy-anyway" },
  { id: 192, text: "I am allowed to choose what feels nourishing to my soul.", tag: "soul-nourish" },
  { id: 193, text: "I trust that my inner wisdom grows each time I honor my truth.", tag: "honor-truth" },
  { id: 194, text: "I am learning to see my progress in the way I care for myself.", tag: "care-progress" },
  { id: 195, text: "I am worthy of being loved in the quiet, in-between moments.", tag: "in-between" },
  { id: 196, text: "I can choose to believe that I am allowed to take up emotional room.", tag: "emotional-room" },
  { id: 197, text: "I am allowed to rest even when others keep going.", tag: "rest-while-others" },
  { id: 198, text: "I trust that my heart can find new ways to feel hopeful.", tag: "new-hope" },
  { id: 199, text: "I am learning to see my boundaries as love letters to myself.", tag: "love-letters" },
  { id: 200, text: "I am worthy of a life that feels like a gentle exhale.", tag: "gentle-exhale" },
  { id: 201, text: "I can let go of the belief that I must always be strong to be loved.", tag: "strong-to-be-loved" },
  { id: 202, text: "I am allowed to choose what feels aligned with my heart.", tag: "heart-aligned" },
  { id: 203, text: "I trust that my inner voice becomes clearer when I honor my needs.", tag: "needs-voice" },
  { id: 204, text: "I am learning to see my healing as a gentle, ongoing process.", tag: "ongoing" },
  { id: 205, text: "I am worthy of being loved in the middle of my uncertainty and growth.", tag: "uncertainty-growth" },
  { id: 206, text: "I can choose to believe that I am not behind; I am on my own timeline.", tag: "own-timeline" },
  { id: 207, text: "I am allowed to rest before I feel completely drained.", tag: "before-drained" },
  { id: 208, text: "I trust that my heart can find softness even after seasons of hardness.", tag: "after-hardness" },
  { id: 209, text: "I am learning to see my boundaries as a way of honoring my worth.", tag: "worth-boundaries" },
  { id: 210, text: "I am worthy of a life that feels gentle, grounded, and real.", tag: "grounded" },
  { id: 211, text: "I can let go of the belief that I must always be improving to be enough.", tag: "enough-as-is" },
  { id: 212, text: "I am allowed to choose what feels true, even if it surprises others.", tag: "surprise" },
  { id: 213, text: "I trust that my inner guidance is leading me toward deeper self-trust.", tag: "self-trust" },
  { id: 214, text: "I am learning to see my healing as a series of gentle returns to myself.", tag: "returning" },
  { id: 215, text: "I am worthy of being loved in the middle of my questions.", tag: "questions" },
  { id: 216, text: "I can choose to believe that I am allowed to take up space in my own story.", tag: "my-story" },
  { id: 217, text: "I am allowed to rest without turning my worth into a performance.", tag: "worth-not-performance" },
  { id: 218, text: "I trust that my heart knows how to find its way back to hope.", tag: "back-to-hope" },
  { id: 219, text: "I am learning to see my needs as invitations to deeper self-care.", tag: "self-care" },
  { id: 220, text: "I am worthy of a life that feels soft, honest, and kind to my soul.", tag: "kind-soul" },
  { id: 221, text: "I can let go of the belief that I must always be okay to be deserving.", tag: "deserving" },
  { id: 222, text: "I am allowed to choose what feels nourishing over what feels numbing.", tag: "numbing" },
  { id: 223, text: "I trust that my inner wisdom grows each time I listen with compassion.", tag: "listen-compassion" },
  { id: 224, text: "I am learning to see my progress in the way I allow myself to rest.", tag: "rest-progress" },
  { id: 225, text: "I am worthy of being loved in the quiet, unremarkable moments.", tag: "unremarkable" },
  { id: 226, text: "I can choose to believe that I am allowed to take up emotional space without apology.", tag: "no-apology" },
  { id: 227, text: "I am allowed to rest even when my to-do list is not finished.", tag: "unfinished" },
  { id: 228, text: "I trust that my heart can find new ways to feel safe and seen.", tag: "safe-and-seen" },
  { id: 229, text: "I am learning to see my boundaries as a way of protecting my peace.", tag: "protect-peace" },
  { id: 230, text: "I am worthy of a life that feels like a soft, steady rhythm.", tag: "steady-rhythm" },
  { id: 231, text: "I can let go of the belief that I must always be strong to be respected.", tag: "respected" },
  { id: 232, text: "I am allowed to choose what feels aligned with my deepest values.", tag: "deep-values" },
  { id: 233, text: "I trust that my inner voice becomes clearer when I create space to listen.", tag: "create-space" },
  { id: 234, text: "I am learning to see my healing as a gentle, ongoing conversation with myself.", tag: "conversation" },
  { id: 235, text: "I am worthy of being loved in the middle of my becoming, not just at the finish line.", tag: "finish-line" },
  { id: 236, text: "I can choose to believe that I am allowed to take up space in every room I enter.", tag: "every-room" },
  { id: 237, text: "I am allowed to rest without needing to justify it to anyone.", tag: "no-justify" },
  { id: 238, text: "I trust that my heart knows how to find its way back to softness.", tag: "back-to-softness" },
  { id: 239, text: "I am learning to see my needs as worthy of being honored, not ignored.", tag: "honored-needs" },
  { id: 240, text: "I am worthy of a life that feels gentle, spacious, and deeply mine.", tag: "deeply-mine" },
  { id: 241, text: "I can let go of the belief that I must always be okay to be loved.", tag: "okay-to-be-loved" },
  { id: 242, text: "I am allowed to choose what feels nourishing to my heart and mind.", tag: "heart-mind" },
  { id: 243, text: "I trust that my inner wisdom grows each time I honor my boundaries and needs.", tag: "honor-both" },
  { id: 244, text: "I am learning to see my progress in the way I speak to myself on hard days.", tag: "hard-days" },
  { id: 245, text: "I am worthy of being loved in the quiet, in-between chapters of my life.", tag: "chapters" },
  { id: 246, text: "I can choose to believe that I am allowed to take up emotional space without shrinking.", tag: "no-shrink" },
  { id: 247, text: "I am allowed to rest even when the world tells me to keep going.", tag: "world-keep-going" },
  { id: 248, text: "I trust that my heart can find new ways to feel hopeful and held.", tag: "hopeful-held" },
  { id: 249, text: "I am learning to see my boundaries as a way of loving myself more deeply.", tag: "deep-love" },
  { id: 250, text: "I am worthy of a life that feels like a soft, steady exhale.", tag: "steady-exhale" },
  { id: 251, text: "I can let go of the belief that I must always be strong to be worthy of care.", tag: "worthy-of-care" },
  { id: 252, text: "I am allowed to choose what feels aligned with my heart’s quiet truth.", tag: "quiet-truth" },
  { id: 253, text: "I trust that my inner voice becomes clearer when I listen without judgment.", tag: "no-judgment" },
  { id: 254, text: "I am learning to see my healing as a gentle, lifelong practice.", tag: "lifelong" },
  { id: 255, text: "I am worthy of being loved in the middle of my questions and doubts.", tag: "questions-doubts" },
  { id: 256, text: "I can choose to believe that I am allowed to take up space in my own healing.", tag: "healing-space" },
  { id: 257, text: "I am allowed to rest without turning my worth into a performance metric.", tag: "no-metric" },
  { id: 258, text: "I trust that my heart knows how to find its way back to trust.", tag: "back-to-trust" },
  { id: 259, text: "I am learning to see my needs as invitations to deeper self-understanding.", tag: "understanding" },
  { id: 260, text: "I am worthy of a life that feels gentle, grounded, and kind to my nervous system.", tag: "kind-nervous" },
  { id: 261, text: "I can let go of the belief that I must always be okay to be deserving of rest.", tag: "deserving-rest" },
  { id: 262, text: "I am allowed to choose what feels nourishing over what feels numbing or distracting.", tag: "nourish-over-numb" },
  { id: 263, text: "I trust that my inner wisdom grows each time I honor my truth, even quietly.", tag: "quiet-truth-honor" },
  { id: 264, text: "I am learning to see my progress in the way I allow myself to be human.", tag: "human" },
  { id: 265, text: "I am worthy of being loved in the ordinary, unfiltered moments of my life.", tag: "unfiltered" },
  { id: 266, text: "I can choose to believe that I am allowed to take up emotional space without apology or explanation.", tag: "no-explanation" },
  { id: 267, text: "I am allowed to rest even when my mind tells me I should be doing more.", tag: "mind-should" },
  { id: 268, text: "I trust that my heart can find new ways to feel safe, soft, and seen.", tag: "safe-soft-seen" },
  { id: 269, text: "I am learning to see my boundaries as a way of honoring my energy and my heart.", tag: "energy-heart" },
  { id: 270, text: "I am worthy of a life that feels like a gentle, honest conversation with myself.", tag: "honest-conversation" },
  { id: 271, text: "I can let go of the belief that I must always be strong to be worthy of love and care.", tag: "love-and-care" },
  { id: 272, text: "I am allowed to choose what feels aligned with my deepest, quietest truth.", tag: "deep-quiet-truth" },
  { id: 273, text: "I trust that my inner voice becomes clearer when I listen with patience and softness.", tag: "patience-softness" },
  { id: 274, text: "I am learning to see my healing as a gentle, ongoing return to myself.", tag: "ongoing-return" },
  { id: 275, text: "I am worthy of being loved in the middle of my uncertainty, growth, and change.", tag: "uncertainty-growth-change" },
  { id: 276, text: "I can choose to believe that I am allowed to take up space in every chapter of my story.", tag: "every-chapter" },
  { id: 277, text: "I am allowed to rest without needing to prove that I have earned it.", tag: "no-proof" },
  { id: 278, text: "I trust that my heart knows how to find its way back to softness and hope.", tag: "softness-hope" },
  { id: 279, text: "I am learning to see my needs as worthy of being met with tenderness and care.", tag: "tenderness-care" },
  { id: 280, text: "I am worthy of a life that feels gentle, spacious, and deeply aligned with who I am.", tag: "deeply-aligned" },
  { id: 281, text: "I can let go of the belief that I must always be okay to be worthy of love and rest.", tag: "love-and-rest" },
  { id: 282, text: "I am allowed to choose what feels nourishing to my body, mind, and spirit.", tag: "body-mind-spirit" },
  { id: 283, text: "I trust that my inner wisdom grows each time I honor my boundaries, needs, and truth.", tag: "boundaries-needs-truth" },
  { id: 284, text: "I am learning to see my progress in the way I allow myself to be imperfect and real.", tag: "imperfect-real" },
  { id: 285, text: "I am worthy of being loved in the quiet, unpolished moments of my life.", tag: "unpolished-moments" },
  { id: 286, text: "I can choose to believe that I am allowed to take up emotional space without shrinking or apologizing.", tag: "no-shrink-no-apology" },
  { id: 287, text: "I am allowed to rest even when the world tells me to keep pushing.", tag: "keep-pushing" },
  { id: 288, text: "I trust that my heart can find new ways to feel safe, hopeful, and held.", tag: "safe-hopeful-held" },
  { id: 289, text: "I am learning to see my boundaries as a way of loving myself in every season.", tag: "every-season" },
  { id: 290, text: "I am worthy of a life that feels like a soft, steady, honest exhale.", tag: "honest-exhale" },
  { id: 291, text: "I can let go of the belief that I must always be strong to be worthy of tenderness.", tag: "worthy-tenderness" },
  { id: 292, text: "I am allowed to choose what feels aligned with my heart, even if it looks different to others.", tag: "different-to-others" },
  { id: 293, text: "I trust that my inner voice becomes clearer when I listen with curiosity instead of judgment.", tag: "curiosity" },
  { id: 294, text: "I am learning to see my healing as a gentle, ongoing act of returning to myself.", tag: "act-of-returning" },
  { id: 295, text: "I am worthy of being loved in the middle of my questions, doubts, and becoming.", tag: "questions-doubts-becoming" },
  { id: 296, text: "I can choose to believe that I am allowed to take up space in my own healing story.", tag: "healing-story" },
  { id: 297, text: "I am allowed to rest without turning my worth into something I must constantly prove.", tag: "no-constant-proof" },
  { id: 298, text: "I trust that my heart knows how to find its way back to trust, softness, and hope.", tag: "trust-softness-hope" },
  { id: 299, text: "I am learning to see my needs as invitations to deeper self-connection.", tag: "self-connection" },
  { id: 300, text: "I am worthy of a life that feels gentle, grounded, and kind to every part of me.", tag: "every-part" },
  { id: 301, text: "I can let go of the belief that I must always be okay to be deserving of love, rest, and care.", tag: "deserving-all" },
  { id: 302, text: "I am allowed to choose what feels nourishing over what feels draining or performative.", tag: "draining-performative" },
  { id: 303, text: "I trust that my inner wisdom grows each time I honor my truth, even in small ways.", tag: "small-truth" },
  { id: 304, text: "I am learning to see my progress in the way I allow myself to be fully human.", tag: "fully-human" },
  { id: 305, text: "I am worthy of being loved in the ordinary, unedited moments of my life.", tag: "unedited" },
  { id: 306, text: "I can choose to believe that I am allowed to take up emotional space without shrinking myself.", tag: "no-shrinking" },
  { id: 307, text: "I am allowed to rest even when my mind tells me I should be doing more to be enough.", tag: "mind-should-enough" },
  { id: 308, text: "I trust that my heart can find new ways to feel safe, soft, hopeful, and held.", tag: "safe-soft-hope-held" },
  { id: 309, text: "I am learning to see my boundaries as a way of honoring my energy, my heart, and my truth.", tag: "energy-heart-truth" },
  { id: 310, text: "I am worthy of a life that feels like a gentle, honest, steady exhale.", tag: "gentle-honest-steady" },
  { id: 311, text: "I can let go of the belief that I must always be strong to be worthy of tenderness and care.", tag: "tenderness-care-worth" },
  { id: 312, text: "I am allowed to choose what feels aligned with my heart’s deepest, quietest knowing.", tag: "deepest-knowing" },
  { id: 313, text: "I trust that my inner voice becomes clearer when I listen with patience, softness, and curiosity.", tag: "patience-soft-curious" },
  { id: 314, text: "I am learning to see my healing as a gentle, ongoing practice of returning to myself.", tag: "practice-return" },
  { id: 315, text: "I am worthy of being loved in the middle of my questions, doubts, and unfolding.", tag: "questions-doubts-unfolding" },
  { id: 316, text: "I can choose to believe that I am allowed to take up space in every part of my story.", tag: "every-part-story" },
  { id: 317, text: "I am allowed to rest without turning my worth into something I must constantly earn.", tag: "no-earn" },
  { id: 318, text: "I trust that my heart knows how to find its way back to trust, softness, and gentle hope.", tag: "gentle-hope" },
  { id: 319, text: "I am learning to see my needs as invitations to deeper self-tending and care.", tag: "self-tending" },
  { id: 320, text: "I am worthy of a life that feels gentle, grounded, spacious, and true to who I am.", tag: "true-to-me" },
  { id: 321, text: "I can let go of the belief that I must always be okay to be deserving of love, rest, and softness.", tag: "deserving-softness" },
  { id: 322, text: "I am allowed to choose what feels nourishing over what feels numbing, draining, or performative.", tag: "nourish-over-all" },
  { id: 323, text: "I trust that my inner wisdom grows each time I honor my truth, even when it feels small.", tag: "small-honoring" },
  { id: 324, text: "I am learning to see my progress in the way I allow myself to be imperfect, tender, and real.", tag: "tender-real" },
  { id: 325, text: "I am worthy of being loved in the ordinary, unfiltered, unpolished moments of my life.", tag: "ordinary-unpolished" },
  { id: 326, text: "I can choose to believe that I am allowed to take up emotional space without shrinking or apologizing for my needs.", tag: "needs-no-apology" },
  { id: 327, text: "I am allowed to rest even when my mind tells me I should be doing more to prove my worth.", tag: "prove-worth" },
  { id: 328, text: "I trust that my heart can find new ways to feel safe, soft, hopeful, and gently held.", tag: "gently-held" },
  { id: 329, text: "I am learning to see my boundaries as a way of honoring my energy, my heart, and my deepest truth.", tag: "deepest-truth" },
  { id: 330, text: "I am worthy of a life that feels like a gentle, honest, steady, and soft exhale.", tag: "soft-exhale" },
  { id: 331, text: "I can let go of the belief that I must always be strong to be worthy of tenderness, care, and rest.", tag: "tender-care-rest" },
  { id: 332, text: "I am allowed to choose what feels aligned with my heart’s deepest, quietest, most honest knowing.", tag: "most-honest" },
  { id: 333, text: "I trust that my inner voice becomes clearer when I listen with patience, softness, curiosity, and compassion.", tag: "compassion-listen" },
  { id: 334, text: "I am learning to see my healing as a gentle, ongoing practice of returning to myself again and again.", tag: "again-and-again" },
  { id: 335, text: "I am worthy of being loved in the middle of my questions, doubts, unfolding, and becoming.", tag: "unfolding-becoming" },
  { id: 336, text: "I can choose to believe that I am allowed to take up space in every chapter, page, and line of my story.", tag: "every-line" },
  { id: 337, text: "I am allowed to rest without turning my worth into something I must constantly earn or prove.", tag: "no-earn-no-prove" },
  { id: 338, text: "I trust that my heart knows how to find its way back to trust, softness, gentle hope, and quiet joy.", tag: "quiet-joy" },
  { id: 339, text: "I am learning to see my needs as invitations to deeper self-tending, care, and understanding.", tag: "tending-understanding" },
  { id: 340, text: "I am worthy of a life that feels gentle, grounded, spacious, honest, and deeply true to who I am.", tag: "deeply-true" },
  { id: 341, text: "I can let go of the belief that I must always be okay to be deserving of love, rest, softness, and care.", tag: "deserving-care" },
  { id: 342, text: "I am allowed to choose what feels nourishing over what feels numbing, draining, performative, or hollow.", tag: "hollow" },
  { id: 343, text: "I trust that my inner wisdom grows each time I honor my truth, even when my voice trembles.", tag: "trembling-truth" },
  { id: 344, text: "I am learning to see my progress in the way I allow myself to be imperfect, tender, real, and human.", tag: "real-human" },
  { id: 345, text: "I am worthy of being loved in the ordinary, unfiltered, unpolished, and unedited moments of my life.", tag: "unedited-moments" },
  { id: 346, text: "I can choose to believe that I am allowed to take up emotional space without shrinking, apologizing, or explaining my needs.", tag: "no-explain-needs" },
  { id: 347, text: "I am allowed to rest even when my mind tells me I should be doing more to earn my place.", tag: "earn-place" },
  { id: 348, text: "I trust that my heart can find new ways to feel safe, soft, hopeful, gently held, and deeply seen.", tag: "deeply-seen" },
  { id: 349, text: "I am learning to see my boundaries as a way of honoring my energy, my heart, my truth, and my future.", tag: "future" },
  { id: 350, text: "I am worthy of a life that feels like a gentle, honest, steady, soft, and spacious exhale.", tag: "spacious-exhale" },
  { id: 351, text: "I can let go of the belief that I must always be strong to be worthy of tenderness, care, rest, and love.", tag: "worthy-of-all" },
  { id: 352, text: "I am allowed to choose what feels aligned with my heart’s deepest, quietest, most honest and tender knowing.", tag: "tender-knowing" },
  { id: 353, text: "I trust that my inner voice becomes clearer when I listen with patience, softness, curiosity, compassion, and love.", tag: "listen-with-love" },
  { id: 354, text: "I am learning to see my healing as a gentle, ongoing practice of returning to myself, again and again, with kindness.", tag: "kind-return" },
  { id: 355, text: "I am worthy of being loved in the middle of my questions, doubts, unfolding, becoming, and softening.", tag: "softening" },
  { id: 356, text: "I can choose to believe that I am allowed to take up space in every chapter, page, line, and margin of my story.", tag: "margins" },
  { id: 357, text: "I am allowed to rest without turning my worth into something I must constantly earn, prove, or defend.", tag: "no-defend" },
  { id: 358, text: "I trust that my heart knows how to find its way back to trust, softness, gentle hope, quiet joy, and deep peace.", tag: "deep-peace" },
  { id: 359, text: "I am learning to see my needs as invitations to deeper self-tending, care, understanding, and compassion.", tag: "needs-compassion" },
  { id: 360, text: "I am worthy of a life that feels gentle, grounded, spacious, honest, kind, and deeply true to who I am becoming.", tag: "true-becoming" },
  { id: 361, text: "I can let go of the belief that I must always be okay to be deserving of love, rest, softness, care, and belonging.", tag: "belonging" },
  { id: 362, text: "I am allowed to choose what feels nourishing over what feels numbing, draining, performative, hollow, or untrue.", tag: "untrue" },
  { id: 363, text: "I trust that my inner wisdom grows each time I honor my truth, even when it feels tender, new, or fragile.", tag: "tender-new" },
  { id: 364, text: "I am learning to see my progress in the way I allow myself to be imperfect, tender, real, human, and still worthy.", tag: "still-worthy" },
  { id: 365, text: "I am worthy of being loved in every version, chapter, and season of who I have been, who I am, and who I am becoming.", tag: "every-version" }
];
